name: Cypress BDD CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      tags:
        description: "Run scenarios with tags (e.g. @smoke, @login, @articles). Leave empty for all tests."
        required: false
        default: "@smoke"
      browser:
        type: choice
        description: "Browser to run tests"
        required: true
        default: "chrome"
        options:
          - chrome
          - edge

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout project
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Clean reports
      - name: Clean previous reports
        run: npm run clean:reports

      # 5. Run tests with manual tag & browser
      - name: Run Cypress Tests
        run: |
          npx cypress run \
            --browser ${{ github.event.inputs.browser || 'chrome' }} \
            --env TAGS="${{ github.event.inputs.tags }}"

      # 6. Generate Cucumber HTML report
      - name: Generate Cucumber HTML Report
        run: npm run report:cucumber

      # 7. Upload report artifact (UPDATED TO v4)
      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-bdd-report
          path: cypress/reports/

      # 8. Deploy HTML report to GitHub Pages
      - name: Deploy Cucumber Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: cypress/reports
